const database = require('./database');

module.exports = {
    getGuildConfig: database.getGuildConfig,
    setGuildKeys: database.setGuildKeys,
    clearGuildKeys: database.clearGuildKeys,
    setGuildNotionConfig: database.setGuildNotionConfig,
    clearGuildNotionConfig: database.clearGuildNotionConfig,
    getNotesChannelId: database.getNotesChannelId,
    setNotesChannelId: database.setNotesChannelId,
    recordSession: database.recordSession,
    getLatestCompletedSession: database.getLatestCompletedSession,
    getGuildStats: database.getGuildStats,
    getRecentSessions: database.getRecentSessions,
    logApiRequest: database.logApiRequest,
    getGuildRequestStats: database.getGuildRequestStats,
    checkGroqDailyLimit: database.checkGroqDailyLimit,
    checkRequestQuota: database.checkRequestQuota,
    setGuildQuota: database.setGuildQuota,
    logAudit: database.logAudit,
    getRecentAuditLogs: database.getRecentAuditLogs,
    updateGuildConfig: database.updateGuildConfig,
    sanitizeAuditDetails: database.sanitizeAuditDetails,
    GROQ_LIMITS: database.GROQ_LIMITS,
};
